# Generated by Django 4.0.6 on 2022-08-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='data',
            new_name='date',
        ),
    ]
